//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Matches")
export class MatchesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Date: string;

@Column({nullable: true})
Opponent: string;

@Column({nullable: true})
Score: string;

@Column({nullable: true})
Location: string;

@Column({nullable: true})
Id: string;


}
