//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("News")
export class NewsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Headline: string;

@Column({nullable: true})
Content: string;

@Column({nullable: true})
Author: string;

@Column({nullable: true})
Date: string;

@Column({nullable: true})
Id: string;


}
