//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Orders")
export class OrdersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Userid: string;

@Column({nullable: true})
Productid: string;

@Column({nullable: true})
Quantity: string;

@Column({nullable: true})
Total: string;

@Column({nullable: true})
Id: string;


}
