//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Payments")
export class PaymentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Orderid: string;

@Column({nullable: true})
Transactionid: string;

@Column({nullable: true})
Status: string;

@Column({nullable: true})
Id: string;


}
