//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Players")
export class PlayersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Name: string;

@Column({nullable: true})
Position: string;

@Column({nullable: true})
Nationality: string;

@Column({nullable: true})
Stats: string;

@Column({nullable: true})
Id: string;


}
