//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Products")
export class ProductsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Title: string;

@Column({nullable: true})
Description: string;

@Column({nullable: true})
Price: string;

@Column({nullable: true})
Category: string;

@Column({nullable: true})
Id: string;


}
