//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("User")
export class UserEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Username: string;

@Column({nullable: true})
Email: string;

@Column({nullable: true})
Phonenumber: string;

@Column({nullable: true})
Shippingaddress: string;

@Column({nullable: true})
Billingaddress: string;

@Column({nullable: true})
Orderhistory: string;

@Column({nullable: true})
Id: string;


}
